remote_theme: pages-themes/cayman@v0.2.0
baseurl: "/blog"
description: "Mathematics, Physics, and Liguistics"
url: "https://YeonsolKim.github.io"
fixed_banner_title: "Abstraction"
banner_color_start: "#000000" 
banner_color_end: "#878787"   