#!/usr/bin/env python3
"""Regenerate the dark-mode block at the end of each stylesheet.

Dark mode swaps black and white but keeps every colour's hue and saturation: each colour
literal gets its HSL lightness inverted (L -> 1 - L), which in RGB is c -> c + 255 - max - min.
Pure red stays pure red, dark grey becomes light grey, and images are untouched.

Every rule that sets a colour is repeated inside `@media (prefers-color-scheme: dark)` with
the inverted colour, in source order, so the cascade resolves the same way in both modes.
Rerun this after changing a colour in one of the stylesheets.
"""
from __future__ import annotations

from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
STYLESHEETS = [
    ROOT / "assets/css/style.scss",
    ROOT / "assets/css/post.css",
    ROOT / "assets/css/index.css",
]
MARKER = "/* Dark mode: generated by scripts/dark_mode_css.py from the colours above; rerun it after editing them. */"

NAMED = {"black": (0, 0, 0), "white": (255, 255, 255), "red": (255, 0, 0), "blue": (0, 0, 255)}
# Inverted colours too dark to read on black, lifted without changing their hue.
LEGIBLE = {"#0000ff": "#7070ff"}

COLOR_LITERAL = re.compile(r"#[0-9a-fA-F]{3,8}\b|rgba?\([^)]*\)|\b(?:" + "|".join(NAMED) + r")\b")
COLOR_PROPERTY = re.compile(r"color|background|border|outline|shadow|^fill$|^stroke$")
# Keyword values of these are repeated too, so a later `color: inherit` still wins in dark mode.
COLOR_ONLY_PROPERTIES = {"color", "background", "background-color", "fill", "stroke"}
# For these only the colour changes; repeating the shorthand would reset widths set elsewhere.
SHORTHANDS = re.compile(r"border(?:-(?:top|right|bottom|left))?|outline")


def invert_lightness(rgb: tuple[int, int, int]) -> tuple[int, int, int]:
    high, low = max(rgb), min(rgb)
    return tuple(c + 255 - high - low for c in rgb)


def dark_color(match: re.Match[str]) -> str:
    literal = match.group(0)
    if literal.startswith("rgb"):
        parts = [p.strip() for p in literal[literal.index("(") + 1 : -1].split(",")]
        rgb = invert_lightness(tuple(int(float(p)) for p in parts[:3]))
        return f"{literal[: literal.index('(')]}({', '.join(map(str, rgb + tuple(parts[3:])))})"
    if literal.startswith("#"):
        digits = literal[1:]
        if len(digits) in (3, 4):
            digits = "".join(c * 2 for c in digits)
        rgb, alpha = tuple(int(digits[i : i + 2], 16) for i in (0, 2, 4)), digits[6:]
    else:
        rgb, alpha = NAMED[literal.lower()], ""
    hex_color = "#" + "".join(f"{c:02x}" for c in invert_lightness(rgb))
    return LEGIBLE.get(hex_color, hex_color) + alpha


def rules(css: str, media: str | None = None):
    """Yield (media query, selector, declarations) for each style rule, descending into @media."""
    pos = 0
    while (start := css.find("{", pos)) >= 0:
        depth, end = 1, start + 1
        while depth:
            depth += {"{": 1, "}": -1}.get(css[end], 0)
            end += 1
        head, body = css[pos:start].strip(), css[start + 1 : end - 1]
        if head.startswith("@media"):
            if "prefers-color-scheme" not in head:  # hand-written colour-scheme rules stay as they are
                yield from rules(body, head.removeprefix("@media").strip())
        elif not head.startswith("@"):
            yield media, head, body
        pos = end


def dark_declarations(body: str) -> list[str]:
    declarations = []
    for declaration in body.split(";"):
        prop, _, value = (part.strip() for part in declaration.partition(":"))
        if not value or not COLOR_PROPERTY.search(prop):
            continue
        literal = COLOR_LITERAL.search(value)
        important = " !important" if "!important" in value else ""
        if literal and SHORTHANDS.fullmatch(prop):
            declarations.append(f"{prop}-color: {dark_color(literal)}{important}")
        elif prop == "background" and "(" not in COLOR_LITERAL.sub("", value):
            declarations.append(f"background-color: {COLOR_LITERAL.sub(dark_color, value)}")
        elif literal or prop in COLOR_ONLY_PROPERTIES:
            declarations.append(f"{prop}: {COLOR_LITERAL.sub(dark_color, value)}")
    return declarations


def dark_block(css: str) -> str:
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    css = re.sub(r"\A---\n.*?---\n", "", css, flags=re.S)
    lines = ["@media (prefers-color-scheme: dark) {"]
    for media, selector, body in rules(css):
        declarations = dark_declarations(body)
        if not declarations:
            continue
        indent = "  "
        if media:
            lines.append(f"  @media {media} {{")
            indent = "    "
        selectors = [s.strip() for s in selector.split(",")]
        lines.append(indent + (",\n" + indent).join(selectors) + " {")
        lines += [f"{indent}  {d};" for d in declarations]
        lines.append(indent + "}")
        if media:
            lines.append("  }")
    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    for path in STYLESHEETS:
        light = path.read_text().split("\n" + MARKER)[0].rstrip("\n")
        path.write_text(f"{light}\n\n{MARKER}\n{dark_block(light)}\n")
        print(f"updated {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
