#!/bin/zsh
# The site's two everyday workflows, behind the Quick Actions "Site - Preview" and
# "Site - Publish" (~/Library/Services), which only call this file:
#
#   zsh scripts/site.zsh preview   Catch up with origin (CI's narration commits), sync the post
#                                  front matter, rebuild, restart `jekyll serve` on :4000.
#                                  Costs nothing and commits nothing.
#   zsh scripts/site.zsh publish   Catch up with origin, sync the front matter, validate (a
#                                  build into a scratch directory + the tests), commit what
#                                  changed with a summarised message (scripts/commit_summary.py),
#                                  push, and follow the CI run in the background. The local
#                                  server is left alone.
#   zsh scripts/site.zsh follow SHA  (started by publish) Wait for the CI run of SHA, report it,
#                                  and pull the narration commit CI makes back.
#
# SITE_REPO=<path> runs against another checkout; SITE_QUIET=1 logs instead of notifying.
#
# Narration is generated by CI only (.github/workflows/pages.yml); nothing here spends money.
# Every step is logged with its duration to ~/Library/Logs/External-Jekyll/site.log, every
# network step has a time limit, and the outcome is a notification.

set -uo pipefail

mode="${1:-}"
repo="${SITE_REPO:-$HOME/External}"
port=4000
log_dir="$HOME/Library/Logs/External-Jekyll"
cache_dir="$HOME/Library/Caches/External-Jekyll"
log="$log_dir/site.log"
server_log="$log_dir/server.log"
lock="$cache_dir/site.lock"
publish_site="$cache_dir/publish-site"
narration_work='synthesise|assemble|no scripts yet|scripts out of date|would remove'

# Automator starts with a bare PATH (Homebrew Ruby/Python/gh, TeX for the TikZ renderer) and
# no locale, in which zsh and cut treat non-ASCII titles and paths as bytes and cut them
# mid-character.
export PATH="/opt/homebrew/opt/ruby/bin:/opt/homebrew/bin:/Library/TeX/texbin:/usr/local/bin:$PATH"
export LANG="${LANG:-en_US.UTF-8}"

case "$mode" in
  preview) title="Site Preview" ;;
  publish) title="Site Publish" ;;
  follow)  title="Site Publish" ;;
  *) print -u2 "usage: site.zsh preview | publish | follow SHA"; exit 2 ;;
esac

cd "$repo" || exit 1
mkdir -p "$log_dir" "$cache_dir"

# -- reporting ---------------------------------------------------------------------------------
say() { print -r -- "$(date '+%F %T') [$mode] $*" >>"$log"; }

notify() {  # notify MESSAGE — quoting is safe: the text goes in as an argument, not as code
  say "notify: $1"
  [[ -n "${SITE_QUIET:-}" ]] && return 0             # tests: no notifications, no Console
  /usr/bin/osascript -e 'on run argv' -e 'display notification (item 1 of argv) with title (item 2 of argv)' \
    -e 'end run' "$1" "$title" >/dev/null 2>&1 || true
}

fail() {  # fail MESSAGE — report, show the log, stop
  say "FAILED: $1"
  notify "Failed: $1"
  [[ -z "${SITE_QUIET:-}" ]] && { /usr/bin/open -a Console "$log" 2>/dev/null || true; }
  exit 1
}

strip_ansi() { /usr/bin/sed $'s/\e\\[[0-9;]*m//g'; }

step_started=0
step() { step_started=$SECONDS; say "▶ $1"; }
step_done() { say "  done in $(( SECONDS - step_started ))s${1:+ — $1}"; }

# -- one run at a time -------------------------------------------------------------------------
take_lock() {  # take_lock WAIT_SECONDS — 0 = give up at once
  local waited=0 holder
  while ! mkdir "$lock" 2>/dev/null; do
    holder=$(cat "$lock/pid" 2>/dev/null)
    # A lock without a pid may be one that is being taken this instant: look once more.
    [[ -z "$holder" ]] && { sleep 1; holder=$(cat "$lock/pid" 2>/dev/null); }
    if [[ -z "$holder" ]] || ! kill -0 "$holder" 2>/dev/null; then
      rm -rf "$lock"                                  # left behind by a run that died
      continue
    fi
    (( waited >= $1 )) && return 1
    sleep 2; (( waited += 2 ))
  done
  print $$ >"$lock/pid"
  print "$mode" >"$lock/mode"
}
release_lock() { [[ "$(cat "$lock/pid" 2>/dev/null)" == "$$" ]] && rm -rf "$lock"; return 0; }

# -- git ---------------------------------------------------------------------------------------
# Bring main up to date with origin/main: fetch with a time limit, then rebase local work on
# top (uncommitted changes are stashed and restored). Returns 1 when origin is unreachable,
# 2 on a conflict (the rebase is aborted, so the tree is as it was), 3 when not on main, 4
# when the rebase worked but the uncommitted changes clash with it — git reports success,
# leaves the files unmerged and keeps the changes in the stash — and 5 while such a conflict
# is still unresolved, so it can never be committed.
catch_up() {
  [[ "$(git symbolic-ref --quiet --short HEAD)" == main ]] || return 3
  [[ -d .git/rebase-merge || -d .git/rebase-apply ]] && return 2
  [[ -n "$(git diff --name-only --diff-filter=U)" ]] && return 5
  /usr/bin/timeout 20 git fetch --quiet origin main >>"$log" 2>&1 || return 1
  git merge-base --is-ancestor origin/main HEAD && return 0     # nothing new
  local stashes=$(git stash list | wc -l)
  if git rebase --autostash origin/main >>"$log" 2>&1; then
    (( $(git stash list | wc -l) > stashes )) && return 4
    return 0
  fi
  git rebase --abort >>"$log" 2>&1 || true
  return 2
}

catch_up_message() {
  case $1 in
    1) print "could not reach origin" ;;
    2) print "conflicts with origin — resolve with git pull --rebase in Terminal" ;;
    3) print "not on the main branch" ;;
    4) print "your uncommitted edits conflict with origin — resolve them (see git status; a copy is in the stash)" ;;
    5) print "unresolved conflicts — see git status" ;;
  esac
}

sync_front_matter() {
  step "front matter"
  python3 scripts/sync_posts_front_matter.py --stabilize >>"$log" 2>&1 ||
    fail "Obsidian is still saving a post. Stop editing and run again."
  step_done
}

# -- local server ------------------------------------------------------------------------------
server_pids() { /usr/sbin/lsof -tiTCP:"$port" -sTCP:LISTEN 2>/dev/null || true; }

ours() {  # a jekyll process started in this repository
  local command_line cwd
  command_line=$(/bin/ps -p "$1" -o command= 2>/dev/null || true)
  cwd=$(/usr/sbin/lsof -a -p "$1" -d cwd -Fn 2>/dev/null | /usr/bin/sed -n 's/^n//p' || true)
  [[ "$command_line" == *jekyll* && "$cwd" == "$repo" ]]
}

stop_server() {
  local pid attempt signal
  for signal in TERM KILL; do
    for pid in ${(f)"$(server_pids)"}; do
      ours "$pid" || fail "port $port is used by another program."
      /bin/kill -$signal "$pid" 2>/dev/null || true
    done
    for attempt in {1..50}; do
      [[ -z "$(server_pids)" ]] && return 0
      sleep 0.1
    done
  done
  fail "could not stop the server on port $port."
}

start_server() {
  /usr/bin/nohup bundle exec jekyll serve --skip-initial-build --host 0.0.0.0 --port "$port" \
    >>"$server_log" 2>&1 </dev/null &!
  local attempt
  for attempt in {1..100}; do
    /usr/bin/curl -fsS "http://127.0.0.1:$port/" >/dev/null 2>&1 && return 0
    sleep 0.2
  done
  return 1
}

# -- build -------------------------------------------------------------------------------------
build_output="$cache_dir/build.out"

build() {  # build [DESTINATION] — output kept in $build_output, warnings counted
  local args=()
  [[ -n "${1:-}" ]] && args=(--destination "$1")
  bundle exec jekyll build "${args[@]}" >"$build_output" 2>&1
  local rc=$?
  strip_ansi <"$build_output" >>"$log"
  return $rc
}
build_warnings() { /usr/bin/grep -c $'\e\\[33m' "$build_output" 2>/dev/null || true; }
build_error() {
  { /usr/bin/grep -m1 $'\e\\[31m' "$build_output" || /usr/bin/grep -m1 -iE 'error' "$build_output" ||
    tail -1 "$build_output"; } 2>/dev/null | strip_ansi |
    /usr/bin/sed -E 's/^ *//; s# in /.*/([^/]+)$# in \1#' | cut -c1-160
}

# -- narration (a report only; CI generates) ---------------------------------------------------
narration_report() {
  [[ -f .env ]] || return 0
  local plan more=""
  local -a names
  plan=$(/usr/bin/timeout 120 python3 -m _narrator publish _site --dry-run 2>&1) || {
    say "narration check failed"; print -r -- "$plan" >>"$log"; return 0; }
  plan=$(print -r -- "$plan" | /usr/bin/grep -E "$narration_work" || true)
  [[ -z "$plan" ]] && return 0
  print -r -- "$plan" >>"$log"
  # "[2.-Compact-Sets] /2026/07/30/2.-Compact-Sets.html  scripts out of date …" → "Compact Sets"
  names=("${(@f)$(print -r -- "$plan" | /usr/bin/sed -nE 's#.*/([^/ ]+)\.html.*#\1#p' |
                   /usr/bin/sed -E 's/^[0-9.]+-//; s/-/ /g')}")
  (( ${#names} > 1 )) && more=" and $(( ${#names} - 1 )) more"
  print -r -- "CI will narrate on publish: ${names[1]}$more"
}

# ==============================================================================================
preview() {
  take_lock 0 || { notify "Already running ($(cat "$lock/mode" 2>/dev/null))."; exit 0; }
  say "==== preview"
  notify "Preview started"

  step "catch up with origin"
  catch_up; local rc=$?
  step_done "$( (( rc )) && catch_up_message $rc || print ok)"
  local notes=()
  (( rc )) && notes+=("not synced: $(catch_up_message $rc)")

  sync_front_matter

  step "stop server"; stop_server; step_done

  step "jekyll build"
  local built=0
  build || built=$?
  step_done "rc=$built"
  local warnings=$(build_warnings)
  (( warnings > 0 )) && notes+=("${warnings} build warning(s)")

  local narration=""
  if (( built == 0 )); then
    step "narration check"; narration=$(narration_report); step_done "${narration:-nothing to do}"
  fi

  # Scripts that speak typography or keep TeX (_narrator/lint.py); hand edits included.
  step "script lint"
  local slips
  slips=$(python3 -m _narrator lint _narration 2>>"$log")
  print -r -- "$slips" >>"$log"
  local -a slip_lines=("${(@f)slips}")
  [[ -n "$slips" ]] && notes+=("${#slip_lines} script slip(s) — see site.log")
  step_done "${slips:+${#slip_lines} slip(s)}"

  step "start server"
  start_server || fail "the server did not start — see $server_log"
  step_done

  if (( built )); then
    # The server is up in watch mode anyway, so fixing the file rebuilds the site.
    fail "build error: $(build_error)"
  fi
  [[ -n "$narration" ]] && notes+=("$narration")
  notify "Ready at localhost:$port${notes:+ · ${(j: · :)notes}}"
  say "ok"
}

# ==============================================================================================
# Staged paths a summarised commit must not carry without a look: secret-like names, big
# files, a top-level entry the repository has never had, or content that looks like a key.
suspicious_staged() {
  local known=(${(f)"$(git ls-tree --name-only HEAD)"}) f size top
  for f in ${(0)"$(git diff --cached --name-only --diff-filter=ACMR -z)"}; do
    case "${f:t}" in
      (.env|.env.*|*.pem|*.key|*.p12|*.pfx|id_rsa*|id_ed25519*|*credentials*)
        print -r -- "$f — looks like a secret" ;;
    esac
    size=$(git cat-file -s ":$f" 2>/dev/null || print 0)
    (( size > 5 * 1024 * 1024 )) && print -r -- "$f — $(( size / 1024 / 1024 )) MB"
    top=${f%%/*}
    (( ${known[(Ie)$top]} )) || print -r -- "$f — new top-level path"
  done
  git diff --cached -U0 --no-color | /usr/bin/grep -qE '^\+(<<<<<<<|>>>>>>>) ' &&
    print -r -- "conflict markers (<<<<<<<) in a staged file"
  git diff --cached -U0 --no-color |
    /usr/bin/grep -E '^\+(.*[^A-Za-z0-9])?(sk-(proj-)?[A-Za-z0-9_-]{20,}|AKIA[0-9A-Z]{16}|-----BEGIN [A-Z ]*PRIVATE KEY-----)' |
    head -3 | while read -r line; do print -r -- "key-like content: ${line:0:40}…"; done
}

publish() {
  take_lock 0 || { notify "Already running ($(cat "$lock/mode" 2>/dev/null))."; exit 0; }
  say "==== publish"
  notify "Publish started"

  step "catch up with origin"
  catch_up; local rc=$?
  step_done "rc=$rc"
  (( rc )) && fail "$(catch_up_message $rc)"

  sync_front_matter

  step "validate: build into $publish_site"
  local built=0
  build "$publish_site" || built=$?
  step_done "rc=$built, $(build_warnings) warning(s)"
  (( built )) && fail "build error: $(build_error)"

  step "validate: tests"
  ruby _tests/test_document_structure.rb >>"$log" 2>&1 || fail "document structure tests failed"
  python3 -m unittest discover -s _tests -p 'test_*.py' >>"$log" 2>&1 || fail "commit summary tests failed"
  python3 -m unittest discover -s _narrator/tests -t . >>"$log" 2>&1 || fail "narration tests failed"
  step_done

  step "stage and commit"
  git add -A . >>"$log" 2>&1 || fail "git add failed"
  local flagged
  flagged=$(suspicious_staged)
  if [[ -n "$flagged" ]]; then
    git reset -q >>"$log" 2>&1
    say "unstaged everything; review these, then commit by hand:"
    print -r -- "$flagged" >>"$log"
    local -a first=("${(@f)flagged}")               # (@): one line must stay one element
    local more=""
    (( ${#first} > 1 )) && more=" (+$(( ${#first} - 1 )) more)"
    fail "check before committing: ${first[1]}$more"
  fi
  local subject=""
  if git diff --cached --quiet; then
    say "  nothing to commit"
  else
    local message
    message=$(python3 scripts/commit_summary.py) || fail "could not write the commit message"
    print -r -- "$message" | git commit -q -F - >>"$log" 2>&1 || fail "git commit failed"
    local -a lines=("${(@f)message}")
    subject=${lines[1]}
    say "  committed: $subject"
  fi
  step_done

  if [[ -z "$(git rev-list origin/main..HEAD)" ]]; then
    notify "Nothing to publish"
    say "nothing to push"
    return 0
  fi

  step "push"
  if ! /usr/bin/timeout 60 git push --quiet origin main >>"$log" 2>&1; then
    # CI may have committed in between: catch up once and try again.
    catch_up; rc=$?
    (( rc )) && fail "push failed — $(catch_up_message $rc)"
    /usr/bin/timeout 60 git push --quiet origin main >>"$log" 2>&1 || fail "push failed"
  fi
  step_done

  local sha=$(git rev-parse HEAD)
  /usr/bin/nohup /bin/zsh "$repo/scripts/site.zsh" follow "$sha" >/dev/null 2>&1 </dev/null &!
  notify "Pushed${subject:+: $subject} · watching the deploy"
  say "pushed ${sha:0:8}; following CI in the background"
}

# ==============================================================================================
follow() {
  local sha="${1:?follow needs a commit}" run="" attempt
  say "==== follow ${sha:0:8}"

  for attempt in {1..24}; do                                    # the run appears within seconds
    run=$(/usr/bin/timeout 20 gh run list --commit "$sha" --workflow pages.yml --limit 1 \
            --json databaseId --jq '.[0].databaseId // empty' 2>>"$log")
    [[ -n "$run" ]] && break
    sleep 5
  done
  [[ -z "$run" ]] && { say "no CI run found"; notify "No CI run found for the push"; exit 1; }
  say "run $run"

  /usr/bin/timeout 5400 gh run watch "$run" --interval 15 >/dev/null 2>>"$log"
  local conclusion
  conclusion=$(/usr/bin/timeout 20 gh run view "$run" --json conclusion --jq .conclusion 2>>"$log")
  if [[ "$conclusion" != success ]]; then
    local failed
    failed=$(/usr/bin/timeout 20 gh run view "$run" --json jobs \
               --jq '[.jobs[].steps[]? | select(.conclusion == "failure") | .name] | first // empty' 2>>"$log")
    say "CI: ${conclusion:-still running after 90 min} ${failed:+($failed)}"
    notify "Deploy failed: ${failed:-${conclusion:-not finished after 90 min}}"
    exit 1
  fi

  # CI commits generated narration back to main; take it now, so the next local run neither
  # regenerates it nor collides with it.
  local scripts=0
  if /usr/bin/timeout 20 git fetch --quiet origin main >>"$log" 2>&1 &&
     [[ -n "$(git log --format=%H --grep='^narration: generated' "$sha"..origin/main)" ]]; then
    scripts=$(git diff --name-only --diff-filter=AM "$sha" origin/main -- _narration |
              /usr/bin/grep -E '\.md$' | /usr/bin/grep -vE '/glossary\.md$|\.new\.md$' | wc -l | tr -d ' ')
  fi

  local pulled=""
  if take_lock 600; then
    catch_up; local rc=$?
    release_lock
    (( rc )) && pulled=" · not pulled: $(catch_up_message $rc)"
  else
    pulled=" · not pulled: another run is busy"
  fi
  say "CI success; narration scripts: $scripts${pulled}"
  notify "Deployed$( (( scripts )) && print " · ${scripts} narration script(s) generated")${pulled}"
}

# The lock is released however the run ends; a signal becomes an exit so the trap runs.
trap release_lock EXIT
trap 'exit 130' INT TERM HUP

case "$mode" in
  preview) preview ;;
  publish) publish ;;
  follow)  follow "${2:-}" ;;
esac
